base:
    seed: &seed 42
model:
    type: DeepseekV3
    path: model_path
    tokenizer_mode: fast
    torch_dtype: torch.float8_e4m3fn
calib:
    name: pileval
    download: False
    path: calib data path
    n_samples: 128
    bs: -1
    seq_len: 512
    preproc: pileval_awq
    seed: *seed
eval:
    eval_pos: [pretrain, transformed, fake_quant]
    name: wikitext2
    download: False
    path: eval data path
    seq_len: 2048
    # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
    # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
    bs: 4
    inference_per_block: True
quant:
    method: Awq
    weight:
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 128
    special:
        trans: True
        # The options for "trans_version" include "v1" and "v2".
        # But their results don't differ significantly.
        trans_version: v2
        # DeepseekV3/R1 not support weight_clip now
        weight_clip: False
        # For 2-bit quantization, setting "clip_sym: False" will yield better results.
        save_mem: False
save:
    save_trans: False
    save_fake: False
    save_path: /path/to/save/
