base:
    seed: &seed 0
model:
    type: Qwen2VL
    # Load Quarot-transformed model
    path: /code/lim42@xiaopeng.com/llmc_test/work/out_qwen25vl_quarot/transformed_model
    torch_dtype: auto
calib:
    name: wikitext2
    download: True
    path: /code/lim42@xiaopeng.com/llmc_test/work/dataset
    n_samples: 512
    bs: 1
    seq_len: 2048
    preproc: wikitext2_gptq
    seed: *seed
eval:
    eval_pos: [fake_quant]
    name: wikitext2
    download: True
    path: /code/lim42@xiaopeng.com/llmc_test/work/dataset
    seq_len: 2048
    # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
    # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
    bs: 1
    inference_per_block: False
quant:
    method: GPTQ
    weight:
        bit: 8
        symmetric: True
        granularity: per_channel
        group_size: -1
        calib_algo: mse
    act:
        bit: 8
        symmetric: True
        granularity: per_token
        calib_algo: minmax
    special:
        actorder: False
        static_groups: True
        percdamp: 0.01
        blocksize: 128
        chunk_num: 4
        true_sequential: True
        online_rotate: False
        fp32_had: True
    quant_out: True
save:
    save_trans: True
    save_fake: False
    save_path: /code/lim42@xiaopeng.com/llmc_test/work/out_qwen25vl_quarot_gptq
